name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          mkdir dist
          cp index.html favicon.svg wrangler.toml dist/
          cp -r images dist/

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 91fa96aa18a0bb0836f188ce5048d18a
          workingDirectory: dist
